apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-petclinic
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5 
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name: petclinic
          image: {{ .Values.container.image }}
          ports:
          - containerPort: 80
            protocol: TCP
          envFrom:
            - configMapRef:
                name: config
          env:
            - name: SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: username
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
