apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  annotations:
    avp.kubernetes.io/path: cubbyhole/test
   # kubernetes.io/service-account.name: myjenkins
type: kubernetes.io/basic-auth
stringData:
  username: Admin
  password: <password>
