apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  annotations:
    avp.kubernetes.io/path: /data/secret/prod
  #  avp.kubernetes.io/kv-version: "1"
   # kubernetes.io/service-account.name: myjenkins
type: kubernetes.io/basic-auth
stringData:
  username: Admin
  password: <mysql_pass>
