apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  annotations:
    avp.kubernetes.io/path: kv/dev
    avp.kubernetes.io/kv-version: "1"
   # kubernetes.io/service-account.name: myjenkins
type: kubernetes.io/basic-auth
stringData:
  username: Admin
  password: <rabbit_user>
