apiVersion: v1
kind: Secret
metadata:
  name: mysecret
#  annotations:
  #  kubernetes.io/service-account.name: myjenkins
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.username }}
  password: {{ .Values.password }}
