apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: {{ .Chart.Name }}   # Selecting PODS with those Labels
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
