apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-petclinic
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name: petclinic
          image: {{ .Values.container.image }}
          ports:
          - containerPort: 8080
#            protocol: TCP
#          env:
#            - name: SECRET_USERNAME
#              valueFrom:
#                secretKeyRef:
#                  name: mysecret
#                  key: username
#            - name: SECRET_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: mysecret
#                  key: password
