on: 
  workflow_dispatch:

name: Alarm

env:
  AWS_REGION: us-east-2                   # set this to your preferred AWS region, e.g. us-west-1

jobs:
  alarmjob:
    name: alarm
    runs-on: ubuntu-latest
#    runs-on: self-hosted   \
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Disable     
      run: |
          aws cloudwatch disable-alarm-actions --alarm-names TargetTracking-table/final-ProvisionedCapacityHigh-b86e277a-05b4-4921-801e-fcd3f2eea07b
      
    - name: Sleep     
      run: |
          aws cloudwatch describe-alarms --alarm-names "TargetTracking-table/final-ProvisionedCapacityHigh-b86e277a-05b4-4921-801e-fcd3f2eea07b"

          sleep 60
          aws cloudwatch describe-alarms --alarm-names "TargetTracking-table/final-ProvisionedCapacityHigh-b86e277a-05b4-4921-801e-fcd3f2eea07b"

    - name: Enable     
      run: |
         aws cloudwatch enable-alarm-actions --alarm-names TargetTracking-table/final-ProvisionedCapacityHigh-b86e277a-05b4-4921-801e-fcd3f2eea07b
